---
# 
# control hpe spp updates
#   
vdebugvar: false

# Supported models
hpe_supported_models: "(G6|G7|Gen8|Gen9|Gen10)"

# Older iLO models do not have an rpm package - will url download
#  this is iLO fw version 2.29 for ilO 2
ilo2_package_url: http://168.94.70.207/linux_utils/CP027871.scexe
#  this is iLO fw version 1.88 for iLO 3
ilo3_package_url: http://16.1.1.21/deployment/CP029099.scexe

##########################
##  control AMS behavior
##
# Control choice to install AMS on AMS capable systems (iLO4+)
install_hpeams: true

# Control choice to configure iLO for community string and trap (used with AMS)
config_ilosnmp:  true

# Control choice to UN-install OS Insight Mgmt agent on AMS capable systems (iLO4+)
uninstall_hpeima: false

# Control choice to install OS Insight Mgmt agen / hphealth on AMS capable systems (iLO4+)
#  this causes SNMP to be used within the OS
install_hpeima: true

# Control choice to set snmpd service params (read community, trap dest, allow & etc)
config_ossnmp: true

# controll the clean up of *extra* rpm (not used rpms) 
hpe_rpm_cleanup: true

# Controll wether to install System Managment Homepage
install_hpesmh: false

# Controll wether to install System Managment Homepage
install_hpesmh: false

# Try to set the 'siteid' if possible by evaluating the hostname
#  regexp pattern check for BDC, Denver, or Richfield hostname standards
site_dc1: "{{ 'DC1' if ( ansible_fqdn | regex_search('^\\w{3}\\d{1}1\\S+') ) else '' }}"
site_dc2: "{{ 'DC2' if ( ansible_fqdn | regex_search('^\\w{3}\\d{1}2\\S+') ) else '' }}"
site_dc3: "{{ 'DC3' if ( ansible_fqdn | regex_search('^\\w{3}\\d{1}3\\S+') ) else '' }}"
# One of the above should be set, other are null....
siteid: "{{ site_dc1 + site_dc2 + site_dc3 }}"


#  Set the subscription manager pool ID
#  If running in DC1:         poolID = 2c90dda25b1f5524015b87e083cd20dc
#  If running in DC2:         poolID = 28de693f5b7c19fd015b87f9f4b404ca
hpe_spp_repo:  "{{ '2c90dda25b1f5524015b87e083cd20dc' if SiteID == 'DC1' else '28de693f5b7c19fd015b87f9f4b404ca' if SiteID == 'DC2' else '2c90dda25b1f5524015b87e083cd20dc' }}"
